# Generated by Django 3.1.2 on 2020-10-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.BooleanField(default=True),
        ),
    ]
