# Generated by Django 3.1.2 on 2020-10-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=17)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('checkbox', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, max_length=30, null=True)),
                ('email2', models.EmailField(blank=True, max_length=30, null=True)),
                ('email3', models.EmailField(blank=True, max_length=30, null=True)),
                ('email4', models.EmailField(blank=True, max_length=30, null=True)),
                ('email5', models.EmailField(blank=True, max_length=30, null=True)),
                ('add_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
