# Generated by Django 3.1.2 on 2020-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
