# Generated by Django 3.1.2 on 2020-10-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
