# Generated by Django 3.1.2 on 2020-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
