# Generated by Django 3.1.2 on 2020-10-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxform', '0003_auto_20201023_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
