# Generated by Django 3.1.2 on 2020-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxform', '0004_auto_20201023_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
